# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Coherent Iterations
email: john@coherentiterations.com
description: > # this means to ignore newlines until "baseurl:"
  This is Coherent Iterations, where I'm documenting my journey to become an iOS and Web Developer. My name is John. I am a full-time engineer and an aspiring developer in my free time.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.coherentiterations.com" # the base hostname & protocol for your site
twitter_username: jdbroadb
twitter:
  username: jdbroadb
github_username:  jdbroadb

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

permalink: /:year/:month/:day/:title

plugins:
  - jekyll-seo-tag

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "John"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
